### ISSUE TITLE
에러가 뜹니다

### ISSUE THREAD

**Issue by Postmodernapple26** [parkgeonhu/sikugeon-bot-server#11]
Note that only Django core commands are listed as settings are not properly configured (error: No module named 'sikugeon_bot.settings').

 'sikugeon_bot.settings' 파일은 어디서 찾을 수 있나요?

**Comment by parkgeonhu** [comment]
@Postmodernapple26 앗 이거 제 개인프로젝트라서 settings.py는 제가 git ignore로 해놨습니다. 혹시 누구신지 알 수 있을까요?

**Comment by parkgeonhu** [comment]
@Postmodernapple26 sikugeon_bot/setting_ex.py 추가해놓았습니다. _ex 지우시고 사용하시면 될 겁니다.
